### ISSUE TITLE
Supported kibana versions

### ISSUE THREAD

**Issue by senty** [outbrain/ob-kb-funnel#1]
Hi,

sorry - i did not find any community forum so i am asking here : What are supported kibana versions ?

thank you very much !

**Comment by yershalom** [comment]
Hi @senty ,
For now 4.x
@roybass When it will support 5.x ?

**Comment by senty** [comment]
Hmm
we are using latest kibana 5.x version :-/
@yershalom How much effort you think it would be to migrate to new version ?

**Comment by roybass** [comment]
Hi!
It should be easy. I'll try to get it working during the weekend.

**Comment by senty** [comment]
Thank you !

**Comment by senty** [comment]
great ... already tested and works fine with version kibana 5.1.1
thanks
