### ISSUE TITLE
Kibana skipping the plugin

### ISSUE THREAD

**Issue by binga** [outbrain/ob-kb-funnel#3]
Hi,

I have installed the plugin on my Macbook El Capitan on Kibana 4.5.4. Installation had no problems. However, when I start kibana, kibana skips this plugin. Here is the log:

log   [18:39:45.310] [warning][plugins] Skipping non-plugin directory at /Users/<>/kibana-4.5.4-darwin-x64/installedPlugins/ob-kb-funnel
log   [18:39:47.650] [info][status][plugin:elasticsearch] Status changed from yellow to green - Kibana index ready

Any solution to this?

**Comment by yershalom** [comment]
Hi @binga ,

I didn't encounter in such case.
Did you find a solution yet?

**Comment by roybass** [comment]
Hi Phani,
Can you list the files under "/Users/<>/kibana-4.5.4-darwin-x64/installedPlugins/ob-kb-funnel" ?
I'll compare to my working version...

Thx
