### ISSUE TITLE
5.2.2 compatibility

### ISSUE THREAD

**Issue by sumia01** [outbrain/ob-kb-funnel#4]
Hi, could you create an 5.2.2 compatible version please?

**Comment by roybass** [comment]
Added release (and tag) v5.2.2 
(I don't have an installation of Kibana 5.2.2 to test this on, would appreciate your assistance..)

**Comment by sumia01** [comment]
Hi, 
I installed it today, it seems it's working.
If you don't want to make new attachment, I attached it. 
Thanks for your quick reply and for your work on this plugin. 

[ob-kb-funnel-5.2.2.zip](https://github.com/outbrain/ob-kb-funnel/files/830441/ob-kb-funnel-5.2.2.zip)

**Comment by roybass** [comment]
Thanks!. Added it to the release
