### ISSUE TITLE
Support for Kibana 5.3.0

### ISSUE THREAD

**Issue by allanlykkechristensen** [outbrain/ob-kb-funnel#5]
Request for plug-in compatible with Kibana 5.3.0

**Comment by yershalom** [comment]
https://github.com/outbrain/ob-kb-funnel/releases/tag/v5.3.0

**Comment by allanlykkechristensen** [comment]
How do I go about creating a release that can be installed? I've seen the source codes, but not the binary that can be installed using `bin/kibana-plugin install URL`
