### ISSUE TITLE
How to use this visualization?

### ISSUE THREAD

**Issue by filmaj** [outbrain/ob-kb-funnel#6]
Hi! Thanks for making this project and open-sourcing it.

I am having trouble using this visualization, though. How does one use it?

I've been looking for a built-in Kibana replacement for this server-side script that queries ElasticSearch and spits out funnel visualizations: https://pypi.python.org/pypi/elastic_funnel

The above, to me, is clear in how to configure it. You need to specify three fields: a timestamp field, an identity field (to group events/documents together), and a stage field (the different parts of the funnel).

It is unclear to me how I use ob-kb-funnel to configure the three fields for a funnel visualization?

In the case of my particular data, documents have a `session` (identity field) and a `message` (stage field), as well as a `timestamp` field.

Thanks for any help!

**Comment by roybass** [comment]
Hi Fil!

The funnel works on [ES buckets](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/search-aggregations-bucket.html). 
Each part of the funnel is represented by a bucket aggregation (which is similar to a "group by" sql query).

I'll try to use your terminology with some assumptions. If you want to see numbers of sessions for each message, you would create an aggregation (buckets) over message, and the metric would count the number of distinct sessions.

In my data set, each document is an event in a website (view, click, etc.). The field "sp_eventTypeId" is the "stage field" and the field "sp_uuid", which identifies a user, is the identity field. Here's an image: 

![image](https://cloud.githubusercontent.com/assets/3296945/25140771/08253de6-246a-11e7-917c-9e65736d826f.png)


Does this help?

**Comment by filmaj** [comment]
Ahhhh... I see. So, one must use a Filters aggregation to pre-define the stages.

So does this mean I have to pre-order the stages as well?

Thanks so much for taking the time to respond - I really appreciate it :)

**Comment by roybass** [comment]
"Filters" is just one way of defining buckets in an ES query.
You could also use terms aggregation to automatically see all stages.
I like to use Filters because I can also add Display Names and control the order easily.

**Comment by roybass** [comment]
@burakkilic  - What do you mean by "chained" ?
